### ISSUE TITLE
40-bit division gives a 16-bit result

### ISSUE THREAD

**Issue by znmeb** [d4ndo/binaryLogic#1]
```
> library(binaryLogic)
> t <- as.binary(50, signed=TRUE, size=5)
> u <- as.binary(-10, signed=TRUE, size=5)
> t
 [1] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0
[39] 1 0
> u
 [1] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1
[39] 1 0
> t %/% u
 [1] 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1
> 
```

**Comment by d4ndo** [comment]
Hi znmeb. 

Thank you for reporting this issue. At the moment »devision« is not supported by version 0.3.4 see https://github.com/d4ndo/binaryLogic#operator.

I was surprised you got an actual result for modulo devision. I will have to check this and think of a good design. For signed values, it should stick to some given size in byte. 
I'm going to fix that hopefully next week.

cheers

**Comment by znmeb** [comment]
I'm using the GitHub version, not the CRAN version, if it matters - the GitHub page listed %/% and %% as available.

My thought on the design is that you should return a result the same size as the longer of the two inputs.

**Comment by d4ndo** [comment]
I have fixed it as you suggested it.

«returns the same size as the longer of the two inputs.«

Thx for reporting. I will close this issue as soon as it is up on cran.
